---
openapi: 3.0.0
info:
   version: 1.3.0
   title: mickey open api specification
   description: mani API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8005
     description: mani
tags:
- name: who
paths:
   "/who":
      post:
         tags:
         -  who
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/who"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  who
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      who:
         type: object
         properties:
            titleID:
               type: "string"
               description: Description
            title:
               type: "string"
               description: Description
            description:
               type: "string"
               description: Description